### ISSUE TITLE
CN should be used over displayName

### ISSUE THREAD

**Issue by liam-middlebrook** [ComputerScienceHouse/conditional#117]
Conditional traditionally used CNs to display the full names of users because that is what we have encouraged users to change to their preferred name to be addressed by. I'm not sure what the motivation to change this was but I'm confused as to why it was grouped into a larger pull request.

**Comment by mbillow** [comment]
It was included instead of concatenating `cn` + `(` + `uid` + `)` and making two requests just to get each person's name. When telling people to update their profiles, we should encourage altering any field that contains their name. It isn't within the scope of Conditional to determine the truth of LDAP and attributes contained within.

**Comment by gambogi** [comment]
Why not just get the `cn` and `uid` in one query then? The `cn` field is intended to be used as @liam-middlebrook described.

**Comment by mbillow** [comment]
Inherently we do now with the new library. The code is just cleaner if we do displayName versus concatenation of different field to get the same result. Breaking that into a separate function, importing that function into most of our blueprints and then replacing instances of displayName, seems unnecessary. We have to assume LDAP information is correct. Users have the same ability to change their displayName as they do their cn.
