### ISSUE TITLE
Add Way to Retroactively Award Attendance for a Committee Meeting

### ISSUE THREAD

**Issue by liam-middlebrook** [ComputerScienceHouse/conditional#50]
Sometimes people walk in right after attendance is submitted and it would be neater convention to add them in after the fact rather than give them separate attendance.

**Comment by audiolion** [comment]
any reason this can't just be where the director is allowed to edit their attendance form (maybe within a week of the created timestamp) which passes a sql update to the database?

**Comment by mbillow** [comment]
So the issue we have is implementation of the front end, not the backend. Modifying SQL in this case is easy and I have done it manually for people I missed in my meetings before. The problem is we have to add the necessary front end pages/elements or better yet decide what those elements are. This is a 90% front end job, the actual endpoint(s) will take almost no time to create.

**Comment by audiolion** [comment]
ok I am going to take a try at it and see where I get.

**Comment by mbillow** [comment]
Fixed by #106
